### ISSUE TITLE
单句单句翻译无法结合上下文信息

### ISSUE THREAD

**Issue by zh-plus** [CuSO4Gem/pytvzhen#12]
一句话一句话翻译能够做并行、速度很快，但是会损失上下文信息，用下来发现需要校对的部分还是比较多（会出现名字不一致等等）

这里推荐一下我搭的轮子：https://github.com/zh-plus/openlrc ，翻译的时候可以结合上下文

我最近也在看类似的项目，想请教下有对比过EdgeTTS和openai的TTS吗？生成中文语音的质量和稳定性方面怎么样？

**Comment by CuSO4Gem** [comment]
EdgeTTS的稳定性无可挑剔，没有出现过问题。
openlrc看起来也是个不错的翻译手段，确实可以合并部分功能。

**Comment by CuSO4Gem** [comment]
EdgeTTS的稳定性无可挑剔，没有出现过问题。
openlrc看起来也是个不错的翻译手段，确实可以合并部分功能。
入Q群交流呀：[697357405](https://qm.qq.com/q/7o3eInvzSE)

**Comment by zh-plus** [comment]
感谢答复！
